### ISSUE TITLE
Add support for 2.5.0

### ISSUE THREAD

**Issue by bml** [sakserv/hadoop-mini-clusters#17]
These mini-clusters have been a huge help to us @sakserv - thanks for all you work!

Are there any plans to add support for the recently released HDP 2.5.0?

**Comment by sakserv** [comment]
Thanks for following up and feedback! I actually started on the HDP 2.5.0 profile work over the weekend. I hope to have an update soon on progress.

**Comment by bml** [comment]
Awesome, thank you!

**Comment by sakserv** [comment]
@bml - I just pushed an update to trunk that leverages HDP 2.5.0.0. Note that I haven't cut a new release yet due to a few items that still need addressed. 

One of the goals of this project was to maintain backwards compatibility for earlier versions of HDP.  The code in trunk breaks this for Storm (packages moved from backtype.storm.* to org.apache.storm*) and YARN (ContainerExecutor#launchContainer signature change). Another issue that is Hortonworks did not publish the Oozie sharelib tarball for this release, I'm working to have that corrected. 

If the above does not impact your use of the project, you should be good to go with the latest commit in trunk. I'm getting ready to go on vacation, so I wanted to get this out before I did. I'll fix the issues above in the coming weeks and will cut a new release.

Please let me know if you run into any issues. Thanks!

**Comment by sakserv** [comment]
Quick update. The oozie sharelib issue has been fixed. I just pushed an update to trunk. The other two issues remain.

**Comment by bml** [comment]
Great, thanks for the quick turnaround!

**Comment by sakserv** [comment]
I just released 0.1.8 which includes support for HDP 2.5.0. Thanks for the report and feedback.
